SET SERVEROUTPUT ON;
SET VERIFY OFF;

declare
	CURSOR TRABAJADORES is SELECT * FROM POBRES FOR UPDATE;
	DATOS EMPLPOYEES%TYPE;
begin
	open TRABAJADORES; 
		LOOP  
			fetch TRABAJADORES into DATOS ;
			EXIT WHEN TRABAJADORES%NOTFOUND;
			INSERT INTO POBRES (SALARY) VALUES(SALARY+(SALARY*0,20))
			DBMS_OUTPUT.PUT_LINE(DATOS.SALARY);
			
		end loop;
	close TRABAJADORES;
end;
/