SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
	N_NUMERO NUMBER(4);
	N_MAXIMO NUMBER(4);
	N_MINIMO NUMBER(4);
	CONTADOR NUMBER := 1;
	N_NOMBRE EMPLOYEES.FIRST_NAME%TYPE  ;
	N_SALARIO EMPLOYEES.SALARY%TYPE ;

BEGIN
	SELECT MIN(EMPLOYEE_ID) INTO N_MINIMO FROM EMPLOYEES;
	SELECT MAX(EMPLOYEE_ID) INTO N_MAXIMO FROM EMPLOYEES;
	WHILE (CONTADOR<10) 
	LOOP
		N_NUMERO := DBMS_RANDOM.VALUE(N_MINIMO,N_MAXIMO);
		SELECT FIRST_NAME INTO N_NOMBRE FROM EMPLOYEES WHERE EMPLOYEE_ID=N_NUMERO;
		SELECT SALARY INTO N_SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID=N_NUMERO;
		DBMS_OUTPUT.PUT_LINE('NOMBRE '||N_NOMBRE||' CON UN  SALARIO DE '||N_SALARIO);
		CONTADOR := CONTADOR + 1;
	END LOOP; 	
	
end;
/