SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
	N_PRIMERO NUMBER(4) :=&PRIMERO;
	N_SEGUNDO NUMBER(4) :=&SEGUNDO;
	N_TERCERO NUMBER(4) :=&TERCERO;
	N_MAYOR number := null ;
	N_MEDIO number := null ;
	N_PEQUE number := null ;


BEGIN
	IF N_PRIMERO>N_SEGUNDO then
		N_MAYOR := N_PRIMERO;
		IF N_PRIMERO<N_TERCERO then
			N_MAYOR := N_TERCERO;
			N_MEDIO := N_PRIMERO;
			N_PEQUE := N_SEGUNDO;
		END IF;
	ELSE
		N_MAYOR := N_SEGUNDO;
		IF N_MAYOR<N_TERCERO then
			N_MAYOR := N_TERCERO;
			N_MEDIO := N_SEGUNDO;
			N_PEQUE := N_PRIMERO;
		END IF;
	END IF;

	IF MOD(N_PRIMERO,2)= 0 then
		DBMS_OUTPUT.PUT_LINE('EL PRIMER NUMERO ES PAR');
	END IF;

	IF MOD(N_SEGUNDO,2)= 0 then
		DBMS_OUTPUT.PUT_LINE('EL SEEGUNDO NUMERO ES PAR');
	END IF;

	IF MOD(N_TERCERO,2)= 0 then
		DBMS_OUTPUT.PUT_LINE('EL TERCER NUMERO ES PAR');
	END IF;
	 

   	DBMS_OUTPUT.PUT_LINE('El MAYOR DE LOS TRES ES ' || N_MAYOR||' EL MEDIANO ' || N_MEDIO ||' EL PEQUE ' ||N_PEQUE);
END;
/