SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
	N_CIUDAD LOCATIONS.STATE_PROVINCE%TYPE;
	D_EMPLEADO EMPLOYEES%ROWTYPE;

  	CURSOR DATOS IS	
	SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID =(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID=(SELECT LOCATION_ID FROM LOCATIONS WHERE STATE_PROVINCE ='&N_CIUDAD'));

BEGIN

	OPEN DATOS;
	LOOP
		FETCH DATOS INTO D_EMPLEADO ;
		EXIT WHEN DATOS%NOTFOUND;
		INSERT INTO TRASLADOS(EMPLOYEE_ID,FIRST_NAME,LAST_NAME) VALUES (D_EMPLEADO.EMPLOYEE_ID,D_EMPLEADO.FIRST_NAME,D_EMPLEADO.LAST_NAME)
		--DBMS_OUTPUT.PUT_LINE(D_EMPLEADO.FIRST_NAME);
	end loop;
	close DATOS;


end;
/