SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
  N_TABLA VARCHAR2(20) :=&TABLA;
  N_COLUMNA VARCHAR2(20) :=&COLUMNA;
  N_VALOR VARCHAR2(20) :=&VALOR;
  N_DATO N_TABLA%ROWTYPE;
  

  CURSOR DATOS IS	
	SELECT
		*
	FROM
		N_TABLA;

BEGIN

	IF N_COLUMNA == N_VALOR THEN
		OPEN DATOS;
		LOOP
			FETCH DATOS INTO N_DATO ;
			EXIT WHEN DATOS%NOTFOUND;
			DBMS_OUTPUT.PUT_LINE(D_DATO.N_COLUMNA);
		end loop;
		close DATOS;
	ELSE 
		DBMS_OUTPUT.PUT_LINE('NO HAY DATOS QUE MOSTRAR PORQUE EL VALOR Y LA COLUMNA NO COINCIDE');
	END IF;

end;
/