SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
	N_PRIMERO NUMBER(4) :=&PRIMERO;
	N_SEGUNDO NUMBER(4) :=&SEGUNDO;
	N_TERCERO NUMBER(4) :=&TERCERO;
	MAYOR number := null ;
BEGIN
	IF N_PRIMERO>N_SEGUNDO then
		MAYOR := N_PRIMERO;
		IF N_PRIMERO<N_TERCERO then
			MAYOR := N_TERCERO;
		END IF;
	ELSE
		MAYOR := N_SEGUNDO;
		IF MAYOR<N_TERCERO then
			MAYOR := N_TERCERO;
		END IF;
	END IF;

   	DBMS_OUTPUT.PUT_LINE('El MAYOR DE LOS TRES ES ' || MAYOR);
end;
/